apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    app: {{ include "nginx-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginx-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-chart.name" . }}
    spec:
      serviceAccountName: {{ include "nginx-chart.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.httpPort }}
            - name: https
              containerPort: {{ .Values.nginx.service.httpsPort }}
          volumeMounts:
            - name: tls-secret
              mountPath: {{ .Values.nginx.https.tlsSecretMountPath }}
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Values.nginx.https.tlsSecretName }}