{{- if .Values.nginx.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-chart.fullname" . }}
spec:
  rules:
    - host: "{{ .Values.nginx.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-chart.fullname" . }}
                port:
                  number: {{ .Values.nginx.service.httpPort }}
{{- end }}