apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.https.tlsSecretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "nginx-chart/files/tls/nginx.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "nginx-chart/files/tls/nginx.key" | b64enc | quote }}