nginx:
  image:
    repository: nginx
    tag: stable
    pullPolicy: Always

  service:
    type: NodePort
    nodePort: 30080
    httpPort: 80
    httpsPort: 443

  ingress:
    enabled: false
    hosts:
      - nginx.example.com
    annotations: {}

  https:
    enabled: false
    tlsSecretName: nginx-tls-secret
    tlsSecretMountPath: "/etc/nginx/tls"
    selfSigned:
      enabled: false
      subject:
        commonName: "nginx-selfsigned"
        organization: "nginx"

serviceAccount:
  create: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
