---
- name: Install Prometheus Node Exporter
  hosts: "{{ host }}"
  become: True
  become_user: root

  vars:
    node_exporter_version: "1.2.2"
    node_exporter_user: "your_user"
    node_exporter_password: "your_password"

    tasks:
    - name: Download Node Exporter binary
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"

    - name: Extract Node Exporter binary
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "/opt/"
        remote_src: true

    - name: Move Node Exporter binary to /usr/local/bin and set ownership
      ansible.builtin.command:
        cmd: "mv /opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/ && chown {{ node_exporter_user }}:{{ node_exporter_user }} /usr/local/bin/node_exporter && chmod 0755 /usr/local/bin/node_exporter"

    - name: Create user for Node Exporter with password
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        system: true
        shell: "/usr/sbin/nologin"
        password: "{{ node_exporter_password | password_hash('sha512') }}"  # Hash the password

    - name: Create systemd service for Node Exporter
      ansible.builtin.template:
        src: "templates/node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
      notify:
        - Restart Node Exporter

  handlers:
    - name: Restart Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted